customhost = "jiunxian99-dbinstance.cksrdsj5psau.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Bait3273"
customdb = "employeeDB"
custombucket = "limjiunxian69-employee"
customregion = "us-east-1"
